spring:
  application:
    name: bakery-inventory

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:change-this-super-secret-key-please-override-in-prod-min-32-bytes}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:864000000}
